### ISSUE TITLE
[MSVC][permissive-][std:c++latest][x86] Failed to build Torque2D on MSVC

### ISSUE THREAD

**Issue by QuellaZhang** [TorqueGameEngines/Torque2D#41]
Torque2D_x86 failed to build with /permissive- or /std:c++latest on MSVC, Torque2D_x64 works fine. Could you please help look at this issue or provide some workarounds? Thanks in advance.

**Build steps:**

1. open VS2019 x86 tools command
2. git clone https://github.com/TorqueGameEngines/Torque2D F:\gitP\TorqueGameEngines\Torque2D
3. set _CL_= /permissive- or set _CL_=/std:c++latest
4. mkdir F:\gitP\TorqueGameEngines\Torque2D\build_x86
5. cd F:\gitP\TorqueGameEngines\Torque2D\build_x86
6. set INCLUDE=F:\gitP\TorqueGameEngines\Torque2D\engine\lib\libogg\include;%INCLUDE%
7. set INCLUDE=F:\gitP\TorqueGameEngines\Torque2D\engine\lib\libvorbis\include;%INCLUDE%
8. set INCLUDE=F:\gitP\TorqueGameEngines\Torque2D\engine\lib\libvorbis\lib;%INCLUDE%
9. msbuild /m /p:Platform=Win32 /p:Configuration=Release /p:WindowsTargetPlatformVersion=10.0.18362.0 "..\engine\compilers\VisualStudio 2019\Torque 2D.sln" /p:UseEnv=true /t:Rebuild /p:Outdir=F:\gitP\TorqueGameEngines\Torque2D\build_x86

**Build.log:**
[build_permissive-.log](https://github.com/TorqueGameEngines/Torque2D/files/7683397/build_permissive-.log)
[build_cpplatest.log](https://github.com/TorqueGameEngines/Torque2D/files/7683425/build_cpplatest.log)

Error info:
**set _CL_= /permissive-**
`F:\gitP\TorqueGameEngines\Torque2D\engine\source\gui\guiListBoxCtrl.h(159,35): error C2838: 'onKeyDown': illegal qualified name in member declaration (compiling source file ..\..\source\gui\editor\guiInspectorTypes.cc) `
`F:\gitP\TorqueGameEngines\Torque2D\engine\source\gui\editor\guiInspector.cc(586,104): error C2664: 'RectI GuiControl::getInnerRect(Point2I &,Point2I &,GuiControlState,GuiControlProfile *)': cannot convert argument 1 from 'Point2I' to 'Point2I &' `
`F:\gitP\TorqueGameEngines\Torque2D\engine\source\gui\editor\guiInspectorTypes.cc(504,107): error C2664: 'Point2I GuiControl::getOuterExtent(Point2I &,GuiControlState,GuiControlProfile *)': cannot convert argument 1 from 'Point2I' to 'Point2I &' `
`F:\gitP\TorqueGameEngines\Torque2D\engine\source\gui\editor\guiInspectorTypes.cc(523,185): error C2664: 'Point2I GuiControl::getOuterExtent(Point2I &,GuiControlState,GuiControlProfile *)': cannot convert argument 1 from 'Point2I' to 'Point2I &' `

**set _CL_= /std:c++latest** : (Suppress by adding "/D_HAS_TR1_NAMESPACE=1 /D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING /D_HAS_STD_BYTE=0",there are other errors.)
`F:\gitP\TorqueGameEngines\Torque2D\engine\source\testing\googleTest\include\gtest\gtest-printers.h(559,1): error C2143: syntax error: missing ';' before '{' (compiling source file ..\..\source\testing\unitTesting.cc) `
`F:\gitP\TorqueGameEngines\Torque2D\engine\source\testing\googleTest\include\gtest\gtest-printers.h(559,1): error C2447: '{': missing function header (old-style formal list?) (compiling source file ..\..\source\testing\unitTesting.cc) `
`F:\gitP\TorqueGameEngines\Torque2D\engine\source\testing\googleTest\include\gtest\gtest-printers.h(718,38): error C2039: 'tr1': is not a member of 'std' (compiling source file ..\..\source\testing\unitTesting.cc) `
`F:\gitP\TorqueGameEngines\Torque2D\engine\source\testing\googleTest\include\gtest\gtest-printers.h(719,24): error C2039: 'tr1': is not a member of 'std' (compiling source file ..\..\source\testing\unitTesting.cc) `
`F:\gitP\TorqueGameEngines\Torque2D\engine\source\testing\googleTest\include\gtest\gtest-printers.h(728,32): error C2039: 'tr1': is not a member of 'std' (compiling source file ..\..\source\testing\unitTesting.cc) `
`F:\gitP\TorqueGameEngines\Torque2D\engine\source\testing\googleTest\include\gtest\gtest-printers.h(731,1): fatal error C1003: error count exceeds 100; stopping compilation (compiling source file ..\..\source\testing\unitTesting.cc)`

**Comment by greenfire27** [comment]
We've fixed a few build errors in the Development branch. Would you mind trying this on the Development branch code? Maybe it's something we've already corrected.

**Comment by QuellaZhang** [comment]
Thanks for your tips, I tried the Development branch, most of the issues have been fixed, and there are still the following errors:

`F:\gitP\TorqueGameEngines\Torque2D\engine\source\2d\core\SpriteBatchItem.h(52,2): error C7626: unnamed class used in typedef name cannot declare members other than non-static data members, member enumerations, or member classes (compiling source file ..\..\source\2d\core\SpriteBatchItem.cc)`
`F:\gitP\TorqueGameEngines\Torque2D\engine\source\2d\core\SpriteBatchItem.h(52,2): error C7626: unnamed class used in typedef name cannot declare members other than non-static data members, member enumerations, or member classes (compiling source file ..\..\source\2d\core\SpriteBatch.cc)`
`F:\gitP\TorqueGameEngines\Torque2D\engine\source\gui\guiColorPicker.cc(475,73): error C2446: '>': no conversion from 'int' to 'S32 [4]' `

**Comment by greenfire27** [comment]
I've done a few check-ins to the development branch that I think should solve this problem. Please confirm that it works now.

**Comment by QuellaZhang** [comment]
Confirmed that these issues have been fixed! Thanks! BTW, when will the fixes be ported to the master branch?

**Comment by greenfire27** [comment]
Glad to hear it!

I'm working through a list of things to get done before the next release. Maybe a month. It's hard to say.
