### ISSUE TITLE
Strange code fragments

### ISSUE THREAD

**Issue by mjunix** [TorqueGameEngines/Torque2D#62]
1. Identical expressions on both sides of `||` operator:
https://github.com/TorqueGameEngines/Torque2D/blob/602694024a4de3e9b29ccfece8043a9e7925213a/engine/source/platform/platformFileIO.cc#L348

2. Unused return value from remove_if:
https://github.com/TorqueGameEngines/Torque2D/blob/602694024a4de3e9b29ccfece8043a9e7925213a/engine/source/Box2D/Particle/b2ParticleSystem.cpp#L2734-L2736

3. Variable assigned to itself:
https://github.com/TorqueGameEngines/Torque2D/blob/602694024a4de3e9b29ccfece8043a9e7925213a/engine/source/game/defaultGame.cc#L596

4. Ternary operator always return same value (should one of the values perhaps be `SI_DPOV2`?):
https://github.com/TorqueGameEngines/Torque2D/blob/602694024a4de3e9b29ccfece8043a9e7925213a/engine/source/platformWin32/winDInputDevice.cc#L994
https://github.com/TorqueGameEngines/Torque2D/blob/602694024a4de3e9b29ccfece8043a9e7925213a/engine/source/platformWin32/winDInputDevice.cc#L1025

5. Parameter `vOut` is array of size 2. Isn't there a possibility of the index `numOut` reaching the value 2 (off by one) inside the if-clause?
https://github.com/TorqueGameEngines/Torque2D/blob/602694024a4de3e9b29ccfece8043a9e7925213a/engine/source/Box2D/Collision/b2Collision.cpp#L201-L231

**Comment by greenfire27** [comment]
Items 2 and 5 are both part of Box2D which we don't actually change the code for - although we will explore updating at some point. Additionally they're both not bugs. In 2, the return value is ignored, but we pass an int by reference that is used. In 5, the only way to get numOut = 2 is if both distance0 and distance1 are negative. If that's true, multiplying them would always give a positive value and you wouldn't be able to get into the final if statement. Clever.

The rest seem like actual odd code. I'll fix 1, 3, and 4.
